# Generated by Django 3.2.15 on 2022-11-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0002_auto_20221104_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='fiyat',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='urun',
            name='isim',
            field=models.CharField(max_length=100, verbose_name='Urun ismi'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='resim',
            field=models.FileField(upload_to='urunler/', verbose_name='Urun resmi'),
        ),
    ]
