# Generated by Django 3.2.15 on 2022-11-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0003_auto_20221105_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carosuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.FileField(upload_to='carousel/', verbose_name='Carousel')),
            ],
        ),
    ]
