# Generated by Django 3.2.15 on 2022-11-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0004_carosuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carosuel',
            name='isim',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
