# Generated by Django 3.2.15 on 2022-11-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0005_carosuel_isim'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carosuel',
        ),
        migrations.AddField(
            model_name='urun',
            name='aciklama',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
