# Generated by Django 3.2.15 on 2022-11-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0006_auto_20221105_0521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='Blog ismi')),
                ('resim', models.FileField(upload_to='Bloglar/', verbose_name='Blog resmi')),
                ('açıklama', models.TextField(max_length=500, null=True)),
                ('saat', models.IntegerField(null=True)),
            ],
        ),
    ]
