# Generated by Django 3.2.15 on 2022-11-05 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0009_rename_i̇ndirim_firsat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Firsat',
            new_name='Blog',
        ),
    ]
