# Generated by Django 3.2.15 on 2022-11-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0010_rename_firsat_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ucuz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='İndirim ismi')),
                ('resim', models.FileField(upload_to='indirimler/', verbose_name='indirim resmi')),
                ('aciklama', models.TextField(max_length=500, null=True)),
                ('saat', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
