# Generated by Django 3.2.15 on 2022-11-06 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0014_auto_20221106_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ucuz',
            old_name='saat',
            new_name='indirim',
        ),
        migrations.DeleteModel(
            name='ShopCart',
        ),
    ]
