# Generated by Django 3.2.15 on 2022-11-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='resim',
            field=models.FileField(upload_to='profilResmi/', verbose_name='Profil Resmi'),
        ),
    ]
