# Generated by Django 3.2.15 on 2022-11-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_account_resim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='resim',
            field=models.FileField(upload_to='profil resimleri/', verbose_name='Hesabım Resmi'),
        ),
    ]
